version: "2.1"

networks:
  frontend:
    name: gateway
    external: true
  backend:

services:
  freshrss_app:
    image: "lscr.io/linuxserver/freshrss:latest"
    container_name: "freshrss"
    networks:
      - frontend
      - backend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "/mnt/docker/freshrss/data:/config"
    restart: "unless-stopped"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.20.11:7514"
        syslog-format: "rfc3164"
        tag: "freshrss"  

    